### ISSUE TITLE
RevX fails to patch new ReX patches

### ISSUE THREAD

**Issue by lou-stro** [kastentop2005/Revancify-X#17]
**Necessary Logs**

```
INFO: Reading dex files 
INFO: Decoding AndroidManifest.xml only, because resources are not needed 
INFO: Skipping add-splash-animation: Excluded by default 
INFO: Skipping change-homepage: Excluded by default 
INFO: Skipping custom-branding-youtube-name: Excluded by default 
INFO: Skipping custom-branding-icon-mmt: Excluded by default 
INFO: Skipping custom-branding-icon-revancify-blue: Excluded by default 
INFO: Skipping custom-branding-icon-revancify-red: Excluded by default 
INFO: Skipping disable-landscape-mode: Excluded by default 
INFO: Skipping enable-debug-logging: Excluded by default 
INFO: Merging YT-Advanced-integrations-v0.115.2.apk 
INFO: Deleting existing resource cache directory 
INFO: Decoding resources 
INFO: Executing patches 
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:319)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:309)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:309)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:38)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:358)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:167)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.NoClassDefFoundError: com/android/tools/smali/dexlib2/AccessFlags
	at app.revanced.patches.youtube.utils.integrations.fingerprints.RemoteEmbeddedPlayerFingerprint.<init>(RemoteEmbeddedPlayerFingerprint.kt:11)
	at app.revanced.patches.youtube.utils.integrations.fingerprints.RemoteEmbeddedPlayerFingerprint.<clinit>(RemoteEmbeddedPlayerFingerprint.kt)
	at app.revanced.patches.youtube.utils.integrations.patch.IntegrationsPatch.<init>(IntegrationsPatch.kt:20)
	... 24 more
Caused by: java.lang.ClassNotFoundException: com.android.tools.smali.dexlib2.AccessFlags
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:440)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 27 more



Variant: nonRoot
Arch: arm64-v8a
App: YouTube v18.30.37
CLI: revanced-cli-v2.22.0.jar
Patches: YT-Advanced-patches-v2.187.2.jar
Integrations: YT-Advanced-integrations-v0.115.2.apk
Patches argument: -i bypass-ambient-mode-restrictions
-i custom-double-tap-length
-i custom-package-name
-i custom-playback-speed
-i custom-seekbar-color
-i default-playback-speed
-i default-video-quality
-i disable-quic-protocol
-i disable-shorts-on-startup
-i disable-auto-captions
-i disable-haptic-feedback
-i disable-hdr-video
-i disable-pip-notification
-i enable-compact-controls-overlay
-i enable-external-browser
-i enable-minimized-playback
-i enable-new-comment-popup-panels
-i enable-new-splash-animation
-i enable-new-thumbnail-preview
-i enable-old-quality-layout
-i enable-open-links-directly
-i enable-seekbar-tapping
-i enable-tablet-mini-player
-i enable-tablet-navigation-bar
-i enable-time-stamps-speed
-i enable-wide-search-bar
-i force-opus-codec
-i force-vp9-codec
-i force-hide-player-button-background
-i force-premium-heading
-i header-switch
-i hide-account-menu
-i hide-auto-player-popup-panels
-i hide-autoplay-button
-i hide-autoplay-preview
-i hide-button-container
-i hide-captions-button
-i hide-cast-button
-i hide-category-bar
-i hide-channel-avatar-section
-i hide-channel-watermark
-i hide-collapse-button
-i hide-comment-component
-i hide-crowdfunding-box
-i hide-description-components
-i hide-double-tap-overlay-filter
-i hide-end-screen-cards
-i hide-end-screen-overlay
-i hide-feed-flyout-panel
-i hide-filmstrip-overlay
-i hide-floating-microphone
-i hide-fullscreen-panels
-i hide-general-ads
-i hide-handle
-i hide-info-cards
-i hide-latest-videos-button
-i hide-layout-components
-i hide-load-more-button
-i hide-mix-playlists
-i hide-music-button
-i hide-navigation-buttons
-i hide-navigation-label
-i hide-player-button-background
-i hide-player-flyout-panel
-i hide-player-overlay-filter
-i hide-previous-next-button
-i hide-quick-actions
-i hide-seek-message
-i hide-seekbar
-i hide-shorts-components
-i hide-snack-bar
-i hide-speed-overlay
-i hide-suggested-actions
-i hide-suggested-video-overlay
-i hide-suggestions-shelf
-i hide-time-stamp
-i hide-tooltip-content
-i hide-trending-searches
-i hide-video-ads
-i language-switch
-i layout-switch
-i materialyou
-i microg-support
-i optimize-resource
-i overlay-buttons
-i return-youtube-dislike
-i settings
-i sponsorblock
-i spoof-app-version
-i spoof-player-parameters
-i swipe-controls
-i theme
-i translations
```

**Comment by YT-Advanced** [comment]
I can confirm it lol

**Comment by IceFox0007** [comment]
Received the same error

INFO: Reading dex files 
INFO: Decoding AndroidManifest.xml only, because resources are not needed 
INFO: Skipping add-splash-animation: Excluded by default 
INFO: Skipping custom-branding-icon-mmt: Excluded by default 
INFO: Skipping custom-branding-icon-revancify-red: Excluded by default 
INFO: Skipping disable-landscape-mode: Excluded by default 
INFO: Skipping enable-debug-logging: Excluded by default 
INFO: Skipping force-hide-player-button-background: Excluded by default 
INFO: Skipping force-premium-heading: Excluded by default 
INFO: Skipping hide-double-tap-overlay-filter: Excluded by default 
INFO: Skipping materialyou: Excluded by default 
INFO: Merging YT-Advanced-integrations-v0.116.2.apk 
INFO: Deleting existing resource cache directory 
INFO: Decoding resources 
INFO: Executing patches 
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:319)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:309)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:309)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:38)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:358)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:167)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.NoClassDefFoundError: com/android/tools/smali/dexlib2/AccessFlags
	at app.revanced.patches.youtube.utils.integrations.fingerprints.RemoteEmbeddedPlayerFingerprint.<init>(RemoteEmbeddedPlayerFingerprint.kt:11)
	at app.revanced.patches.youtube.utils.integrations.fingerprints.RemoteEmbeddedPlayerFingerprint.<clinit>(RemoteEmbeddedPlayerFingerprint.kt)
	at app.revanced.patches.youtube.utils.integrations.patch.IntegrationsPatch.<init>(IntegrationsPatch.kt:20)
	... 24 more
Caused by: java.lang.ClassNotFoundException: com.android.tools.smali.dexlib2.AccessFlags
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:440)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 27 more



Variant: nonRoot
Arch: arm64-v8a
App: YouTube v18.31.40
CLI: revanced-cli-v2.22.0.jar
Patches: YT-Advanced-patches-v2.188.0.jar
Integrations: YT-Advanced-integrations-v0.116.2.apk
Patches argument: -i bypass-ambient-mode-restrictions
-i change-homepage
-i custom-branding-youtube-name
-i custom-branding-icon-revancify-blue
-i custom-double-tap-length
-i custom-package-name
-i custom-playback-speed
-i custom-seekbar-color
-i default-playback-speed
-i default-video-quality
-i disable-quic-protocol
-i disable-shorts-on-startup
-i disable-auto-captions
-i disable-haptic-feedback
-i disable-hdr-video
-i disable-pip-notification
-i enable-compact-controls-overlay
-i enable-external-browser
-i enable-minimized-playback
-i enable-new-comment-popup-panels
-i enable-new-splash-animation
-i enable-new-thumbnail-preview
-i enable-old-quality-layout
-i enable-open-links-directly
-i enable-seekbar-tapping
-i enable-tablet-mini-player
-i enable-tablet-navigation-bar
-i enable-time-stamps-speed
-i enable-wide-search-bar
-i force-opus-codec
-i force-vp9-codec
-i header-switch
-i hide-account-menu
-i hide-auto-player-popup-panels
-i hide-autoplay-button
-i hide-autoplay-preview
-i hide-button-container
-i hide-captions-button
-i hide-cast-button
-i hide-category-bar
-i hide-channel-avatar-section
-i hide-channel-watermark
-i hide-collapse-button
-i hide-comment-component
-i hide-crowdfunding-box
-i hide-description-components
-i hide-end-screen-cards
-i hide-end-screen-overlay
-i hide-feed-flyout-panel
-i hide-filmstrip-overlay
-i hide-floating-microphone
-i hide-fullscreen-panels
-i hide-general-ads
-i hide-handle
-i hide-info-cards
-i hide-latest-videos-button
-i hide-layout-components
-i hide-load-more-button
-i hide-mix-playlists
-i hide-music-button
-i hide-navigation-buttons
-i hide-navigation-label
-i hide-player-button-background
-i hide-player-flyout-panel
-i hide-player-overlay-filter
-i hide-previous-next-button
-i hide-quick-actions
-i hide-seek-message
-i hide-seekbar
-i hide-shorts-components
-i hide-snack-bar
-i hide-speed-overlay
-i hide-suggested-actions
-i hide-suggested-video-overlay
-i hide-suggestions-shelf
-i hide-time-stamp
-i hide-tooltip-content
-i hide-trending-searches
-i hide-video-ads
-i language-switch
-i layout-switch
-i microg-support
-i optimize-resource
-i overlay-buttons
-i return-youtube-dislike
-i settings
-i sponsorblock
-i spoof-app-version
-i spoof-player-parameters
-i swipe-controls
-i theme
-i translations

**Comment by vhick** [comment]
Also receiving error while patching YouTube:

Thanks!

> INFO: Reading dex files 
INFO: Decoding AndroidManifest.xml only, because resources are not needed 
INFO: Skipping add-splash-animation: Excluded by default 
INFO: Skipping custom-branding-icon-mmt: Excluded by default 
INFO: Skipping custom-branding-icon-revancify-red: Excluded by default 
INFO: Skipping disable-landscape-mode: Excluded by default 
INFO: Skipping enable-debug-logging: Excluded by default 
INFO: Skipping force-hide-player-button-background: Excluded by default 
INFO: Skipping force-premium-heading: Excluded by default 
INFO: Skipping hide-double-tap-overlay-filter: Excluded by default 
INFO: Skipping materialyou: Excluded by default 
INFO: Merging YT-Advanced-integrations-v0.116.2.apk 
INFO: Deleting existing resource cache directory 
INFO: Decoding resources 
INFO: Executing patches 
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:319)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:309)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:309)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:38)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:358)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:167)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.NoClassDefFoundError: com/android/tools/smali/dexlib2/AccessFlags
	at app.revanced.patches.youtube.utils.integrations.fingerprints.RemoteEmbeddedPlayerFingerprint.<init>(RemoteEmbeddedPlayerFingerprint.kt:11)
	at app.revanced.patches.youtube.utils.integrations.fingerprints.RemoteEmbeddedPlayerFingerprint.<clinit>(RemoteEmbeddedPlayerFingerprint.kt)
	at app.revanced.patches.youtube.utils.integrations.patch.IntegrationsPatch.<init>(IntegrationsPatch.kt:20)
	... 24 more
Caused by: java.lang.ClassNotFoundException: com.android.tools.smali.dexlib2.AccessFlags
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:440)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 27 more



Variant: nonRoot
Arch: arm64-v8a
App: YouTube v18.31.40
CLI: revanced-cli-v2.22.0.jar
Patches: YT-Advanced-patches-v2.188.0.jar
Integrations: YT-Advanced-integrations-v0.116.2.apk
Patches argument: -i bypass-ambient-mode-restrictions
-i change-homepage
-i custom-branding-youtube-name
-i custom-branding-icon-revancify-blue
-i custom-double-tap-length
-i custom-package-name
-i custom-playback-speed
-i custom-seekbar-color
-i default-playback-speed
-i default-video-quality
-i disable-quic-protocol
-i disable-shorts-on-startup
-i disable-auto-captions
-i disable-haptic-feedback
-i disable-hdr-video
-i disable-pip-notification
-i enable-compact-controls-overlay
-i enable-external-browser
-i enable-minimized-playback
-i enable-new-comment-popup-panels
-i enable-new-splash-animation
-i enable-new-thumbnail-preview
-i enable-old-quality-layout
-i enable-open-links-directly
-i enable-seekbar-tapping
-i enable-tablet-mini-player
-i enable-tablet-navigation-bar
-i enable-time-stamps-speed
-i enable-wide-search-bar
-i force-opus-codec
-i force-vp9-codec
-i header-switch
-i hide-account-menu
-i hide-auto-player-popup-panels
-i hide-autoplay-button
-i hide-autoplay-preview
-i hide-button-container
-i hide-captions-button
-i hide-cast-button
-i hide-category-bar
-i hide-channel-avatar-section
-i hide-channel-watermark
-i hide-collapse-button
-i hide-comment-component
-i hide-crowdfunding-box
-i hide-description-components
-i hide-end-screen-cards
-i hide-end-screen-overlay
-i hide-feed-flyout-panel
-i hide-filmstrip-overlay
-i hide-floating-microphone
-i hide-fullscreen-panels
-i hide-general-ads
-i hide-handle
-i hide-info-cards
-i hide-latest-videos-button
-i hide-layout-components
-i hide-load-more-button
-i hide-mix-playlists
-i hide-music-button
-i hide-navigation-buttons
-i hide-navigation-label
-i hide-player-button-background
-i hide-player-flyout-panel
-i hide-player-overlay-filter
-i hide-previous-next-button
-i hide-quick-actions
-i hide-seek-message
-i hide-seekbar
-i hide-shorts-components
-i hide-snack-bar
-i hide-speed-overlay
-i hide-suggested-actions
-i hide-suggested-video-overlay
-i hide-suggestions-shelf
-i hide-time-stamp
-i hide-tooltip-content
-i hide-trending-searches
-i hide-video-ads
-i language-switch
-i layout-switch
-i microg-support
-i optimize-resource
-i overlay-buttons
-i return-youtube-dislike
-i settings
-i sponsorblock
-i spoof-app-version
-i spoof-player-parameters
-i swipe-controls
-i theme
-i translations
