### ISSUE TITLE
Failed to patch

### ISSUE THREAD

**Issue by D3SOX** [kastentop2005/Revancify-X#6]
```
INFO: Reading dex files 
INFO: Loading resource table... 
INFO: Decoding AndroidManifest.xml only, because resources are not needed 
INFO: Loading resource table from file: revanced-cache/1.apk 
INFO: Skipping add-splash-animation: Excluded by default 
INFO: Skipping custom-branding-youtube-name: Excluded by default 
INFO: Skipping custom-branding-icon-mmt: Excluded by default 
INFO: Skipping custom-branding-icon-revancify-blue: Excluded by default 
INFO: Skipping custom-branding-icon-revancify-red: Excluded by default 
INFO: Skipping disable-landscape-mode: Excluded by default 
INFO: Skipping enable-debug-logging: Excluded by default 
INFO: Skipping force-hide-player-button-background: Excluded by default 
INFO: Skipping force-premium-heading: Excluded by default 
INFO: Skipping hide-double-tap-overlay-filter: Excluded by default 
INFO: Skipping microg-support: Excluded by default 
INFO: Skipping theme: Excluded by default 
INFO: Merging inotia00-integrations-v0.114.8.apk 
INFO: Loading resource table... 
INFO: Deleting existing resource cache directory 
INFO: Decoding resources 
INFO: Decoding AndroidManifest.xml with resources... 
INFO: Loading resource table from file: revanced-cache/1.apk 
INFO: Regular manifest package... 
INFO: Decoding file-resources... 
INFO: Decoding values */* XMLs... 
INFO: Executing patches 
INFO: Bypass ambient mode restrictions succeeded 
INFO: Change homepage succeeded 
INFO: Custom double tap length succeeded 
INFO: Custom package name succeeded 
INFO: Custom playback speed succeeded 
INFO: Custom seekbar color succeeded 
INFO: Default playback speed succeeded 
INFO: Default video quality succeeded 
INFO: Disable QUIC protocol succeeded 
INFO: Disable Shorts on startup succeeded 
INFO: Disable auto captions succeeded 
INFO: Disable haptic feedback succeeded 
INFO: Disable hdr video succeeded 
INFO: Disable pip notification succeeded 
INFO: Enable compact controls overlay succeeded 
INFO: Enable external browser succeeded 
INFO: Enable minimized playback succeeded 
INFO: Enable new comment popup panels succeeded 
INFO: Enable new splash animation succeeded 
INFO: Enable new thumbnail preview succeeded 
INFO: Enable old quality layout succeeded 
INFO: Enable open links directly succeeded 
INFO: Enable seekbar tapping succeeded 
INFO: Enable tablet mini player succeeded 
INFO: Enable tablet navigation bar succeeded 
INFO: Enable time stamps speed succeeded 
INFO: Enable wide search bar succeeded 
INFO: Force OPUS codec succeeded 
INFO: Force VP9 codec succeeded 
INFO: Header switch succeeded 
INFO: Hide Shorts components succeeded 
INFO: Hide account menu succeeded 
INFO: Hide auto player popup panels succeeded 
INFO: Hide autoplay button succeeded 
INFO: Hide autoplay preview succeeded 
INFO: Hide button container succeeded 
INFO: Hide captions button succeeded 
INFO: Hide cast button succeeded 
INFO: Hide category bar succeeded 
INFO: Hide channel avatar section succeeded 
INFO: Hide channel watermark succeeded 
INFO: Hide collapse button succeeded 
INFO: Hide comment component succeeded 
INFO: Hide crowdfunding box succeeded 
INFO: Hide description components succeeded 
INFO: Hide end screen cards succeeded 
INFO: Hide end screen overlay succeeded 
INFO: Hide feed flyout panel succeeded 
INFO: Hide filmstrip overlay succeeded 
INFO: Hide floating microphone succeeded 
INFO: Hide fullscreen panels succeeded 
INFO: Hide general ads succeeded 
INFO: Hide handle succeeded 
INFO: Hide info cards succeeded 
INFO: Hide layout components succeeded 
INFO: Hide load more button succeeded 
INFO: Hide mix playlists succeeded 
INFO: Hide music button succeeded 
INFO: Hide navigation buttons succeeded 
INFO: Hide navigation label succeeded 
INFO: Hide player button background succeeded 
INFO: Hide player flyout panel succeeded 
INFO: Hide player overlay filter succeeded 
INFO: Hide previous next button succeeded 
INFO: Hide quick actions succeeded 
INFO: Hide seek message succeeded 
INFO: Hide seekbar succeeded 
INFO: Hide snack bar succeeded 
INFO: Hide speed overlay succeeded 
INFO: Hide suggested actions succeeded 
INFO: Hide suggested video overlay succeeded 
INFO: Hide suggestions shelf succeeded 
INFO: Hide time stamp succeeded 
INFO: Hide tooltip content succeeded 
INFO: Hide trending searches succeeded 
INFO: Hide video ads succeeded 
INFO: Language switch succeeded 
INFO: Layout switch succeeded 
INFO: MaterialYou succeeded 
INFO: Optimize resource succeeded 
INFO: Overlay buttons succeeded 
INFO: Return YouTube Dislike succeeded 
INFO: Settings succeeded 
INFO: Sponsorblock succeeded 
INFO: Spoof app version succeeded 
INFO: Spoof player parameters succeeded 
INFO: Swipe controls succeeded 
INFO: Translations succeeded 
INFO: Compiling resources 
WARNING: aapt: binary could not be read: /data/data/com.termux/files/home/RevancifyX-data/aapt2_arm64-v8a (defaulting to $PATH binary) 
WARNING: error: resource 'drawable/$$buenos_aires_animation_dark__1__0' has invalid entry name '$$buenos_aires_animation_dark__1__0. 
WARNING: error: resource 'drawable/$$buenos_aires_animation_dark__1__1' has invalid entry name '$$buenos_aires_animation_dark__1__1. 
WARNING: error: resource 'drawable/$$buenos_aires_animation_dark__1__10' has invalid entry name '$$buenos_aires_animation_dark__1__10. 
WARNING: error: resource 'drawable/$$buenos_aires_animation_dark__1__11' has invalid entry name '$$buenos_aires_animation_dark__1__11. 
WARNING: error: resource 'drawable/$$buenos_aires_animation_dark__1__12' has invalid entry name '$$buenos_aires_animation_dark__1__12. 
WARNING: error: resource 'drawable/$$buenos_aires_animation_dark__1__13' has invalid entry name '$$buenos_aires_animation_dark__1__13. 
WARNING: error: resource 'drawable/$$buenos_aires_animation_dark__1__14' has invalid entry name '$$buenos_aires_animation_dark__1__14. 
WARNING: error: resource 'drawable/$$buenos_aires_animation_dark__1__2' has invalid entry name '$$buenos_aires_animation_dark__1__2. 
WARNING: error: resource 'drawable/$$buenos_aires_animation_dark__1__3' has invalid entry name '$$buenos_aires_animation_dark__1__3. 
WARNING: error: resource 'drawable/$$buenos_aires_animation_dark__1__4' has invalid entry name '$$buenos_aires_animation_dark__1__4. 
WARNING: error: resource 'drawable/$$buenos_aires_animation_dark__1__5' has invalid entry name '$$buenos_aires_animation_dark__1__5. 
WARNING: error: resource 'drawable/$$buenos_aires_animation_dark__1__6' has invalid entry name '$$buenos_aires_animation_dark__1__6. 
WARNING: error: resource 'drawable/$$buenos_aires_animation_dark__1__7' has invalid entry name '$$buenos_aires_animation_dark__1__7. 
WARNING: error: resource 'drawable/$$buenos_aires_animation_dark__1__8' has invalid entry name '$$buenos_aires_animation_dark__1__8. 
WARNING: error: resource 'drawable/$$buenos_aires_animation_dark__1__9' has invalid entry name '$$buenos_aires_animation_dark__1__9. 
WARNING: error: resource 'drawable/$$buenos_aires_animation_dark__20__0' has invalid entry name '$$buenos_aires_animation_dark__20__0. 
WARNING: error: resource 'drawable/$$buenos_aires_animation_dark__20__1' has invalid entry name '$$buenos_aires_animation_dark__20__1. 
WARNING: error: resource 'drawable/$$buenos_aires_animation_dark__23__0' has invalid entry name '$$buenos_aires_animation_dark__23__0. 
WARNING: error: resource 'drawable/$$buenos_aires_animation_dark__23__1' has invalid entry name '$$buenos_aires_animation_dark__23__1. 
WARNING: error: resource 'drawable/$$buenos_aires_animation_dark__23__2' has invalid entry name '$$buenos_aires_animation_dark__23__2. 
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [aapt2, compile, --dir, /data/data/com.termux/files/home/RevancifyX-data/revanced-cache/res, --legacy, -o, /data/data/com.termux/files/home/RevancifyX-data/revanced-cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:366)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:620)
	at app.revanced.patcher.Patcher.save(Patcher.kt:132)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:21)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:173)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [aapt2, compile, --dir, /data/data/com.termux/files/home/RevancifyX-data/revanced-cache/res, --legacy, -o, /data/data/com.termux/files/home/RevancifyX-data/revanced-cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:362)
	... 13 more



Variant: root
Arch: arm64-v8a
App: YouTube v18.27.36
CLI: inotia00-cli-v2.22.2.jar
Patches: inotia00-patches-v2.186.8.jar
Integrations: inotia00-integrations-v0.114.8.apk
Patches argument: -i bypass-ambient-mode-restrictions
-i change-homepage
-i custom-double-tap-length
-i custom-package-name
-i custom-playback-speed
-i custom-seekbar-color
-i default-playback-speed
-i default-video-quality
-i disable-quic-protocol
-i disable-shorts-on-startup
-i disable-auto-captions
-i disable-haptic-feedback
-i disable-hdr-video
-i disable-pip-notification
-i enable-compact-controls-overlay
-i enable-external-browser
-i enable-minimized-playback
-i enable-new-comment-popup-panels
-i enable-new-splash-animation
-i enable-new-thumbnail-preview
-i enable-old-quality-layout
-i enable-open-links-directly
-i enable-seekbar-tapping
-i enable-tablet-mini-player
-i enable-tablet-navigation-bar
-i enable-time-stamps-speed
-i enable-wide-search-bar
-i force-opus-codec
-i force-vp9-codec
-i header-switch
-i hide-shorts-components
-i hide-account-menu
-i hide-auto-player-popup-panels
-i hide-autoplay-button
-i hide-autoplay-preview
-i hide-button-container
-i hide-captions-button
-i hide-cast-button
-i hide-category-bar
-i hide-channel-avatar-section
-i hide-channel-watermark
-i hide-collapse-button
-i hide-comment-component
-i hide-crowdfunding-box
-i hide-description-components
-i hide-end-screen-cards
-i hide-end-screen-overlay
-i hide-feed-flyout-panel
-i hide-filmstrip-overlay
-i hide-floating-microphone
-i hide-fullscreen-panels
-i hide-general-ads
-i hide-handle
-i hide-info-cards
-i hide-layout-components
-i hide-load-more-button
-i hide-mix-playlists
-i hide-music-button
-i hide-navigation-buttons
-i hide-navigation-label
-i hide-player-button-background
-i hide-player-flyout-panel
-i hide-player-overlay-filter
-i hide-previous-next-button
-i hide-quick-actions
-i hide-seek-message
-i hide-seekbar
-i hide-snack-bar
-i hide-speed-overlay
-i hide-suggested-actions
-i hide-suggested-video-overlay
-i hide-suggestions-shelf
-i hide-time-stamp
-i hide-tooltip-content
-i hide-trending-searches
-i hide-video-ads
-i language-switch
-i layout-switch
-i materialyou
-i optimize-resource
-i overlay-buttons
-i return-youtube-dislike
-i settings
-i sponsorblock
-i spoof-app-version
-i spoof-player-parameters
-i swipe-controls
-i translations
```

**Comment by kastentop2005** [comment]
It must be fixed now (at least for armv8)
